import { test, before, after } from 'node:test';
import assert from 'node:assert/strict';
import { launch, withPhone, waitSaved } from './harness.js';
import { uuid } from '../../shared/ids.js';
let browser;
before(async () => { browser = await launch(); });
after(async () => { await browser.close(); });
const item = (text, attrs = {}) => ({ type: 'taskItem', attrs: { id: uuid(), checked: false, ...attrs }, content: [{ type: 'paragraph', content: [{ type: 'text', text }] }] });
const seed = (app, id, items) => app.api('PUT', `/api/notes/${id}`, { baseRevision: 0, kind: 'note', date: '2026-10-05', tags: ['test'], docFormat: 1, doc: { type: 'doc', content: [{ type: 'taskList', content: items }] } });

test('clock times change task sections and manual time survives save, reopen and typing', () => withPhone(browser, async ({ app, page }) => {
  const id = uuid();
  await seed(app, id, [item('Call starts today at 6pm'), item('Email due today at 5pm')]);
  await page.goto(`${app.url}/#/tasks`);
  await page.getByTestId('toggle-later').tap();
  assert.match(await page.getByTestId('section-later').innerText(), /Call/);
  assert.match(await page.getByTestId('section-today').innerText(), /17:00/);
  await page.clock.fastForward(91 * 60 * 1000);
  await page.getByTestId('section-overdue').waitFor();
  assert.match(await page.getByTestId('section-overdue').innerText(), /Email/);
  assert.match(await page.getByTestId('section-anytime').innerText(), /Call/);
  await page.goto(`${app.url}/#/n/${id}`);
  const editor = page.locator('.note-text[contenteditable="true"]');
  await editor.locator('p').nth(1).tap();
  await page.getByTestId('tb-taskdates').tap();
  await page.getByTestId('input-due-time').fill('19:30');
  await page.getByTestId('task-sheet-done').tap();
  await waitSaved(page);
  await page.reload();
  await editor.locator('p').nth(1).tap();
  await page.getByTestId('tb-taskdates').tap();
  assert.equal(await page.getByTestId('input-due-time').inputValue(), '19:30');
  await page.getByTestId('task-sheet-done').tap();
  await editor.locator('p').nth(1).tap();
  await page.keyboard.press('End'); await page.keyboard.type(' safely');
  await waitSaved(page);
  const doc = (await app.api('GET', `/api/notes/${id}`)).json.note.doc;
  assert.equal(doc.content[0].content[1].attrs.dueTime, '19:30');
  assert.match(doc.content[0].content[1].content[0].content.map((t) => t.text || '').join(''), /safely/);
}, { clockTime: new Date('2026-10-05T22:30:00Z') }));

test('calendar picks ranges across months, supports reversed endpoints, Escape, and phone width', () => withPhone(browser, async ({ app, page }) => {
  const id = uuid();
  await seed(app, id, [item('September task', { checked: true, completedAt: '2026-09-30T18:00:00.000Z' }), item('October task', { checked: true, completedAt: '2026-10-05T18:00:00.000Z' })]);
  await page.goto(`${app.url}/#/n/${id}`);
  await page.getByTestId('task-archive').locator(':scope > summary').tap();
  await page.getByTestId('archive-calendar').tap();
  const dialog = page.getByRole('dialog', { name: 'Task history date range calendar' });
  await dialog.getByRole('button', { name: '2026-10-05', exact: true }).tap();
  await dialog.getByRole('button', { name: 'Previous month' }).tap();
  await dialog.getByRole('button', { name: '2026-09-30', exact: true }).tap();
  assert.equal(await dialog.count(), 0);
  assert.equal(await page.getByTestId('archive-task').count(), 2);
  await page.getByTestId('archive-calendar').tap();
  assert.equal(await page.getByTestId('archive-from').inputValue(), '2026-09-30');
  assert.equal(await page.getByTestId('archive-to').inputValue(), '2026-10-05');
  const bounds = await dialog.boundingBox(); assert.ok(bounds.x >= 0 && bounds.x + bounds.width <= 360);
  assert.ok(bounds.y >= 64 && bounds.y + bounds.height <= 780 - 60, 'picker clears both toolbars');
  await page.keyboard.press('Escape');
  assert.equal(await dialog.count(), 0);
  assert.equal(await page.getByTestId('archive-calendar').evaluate((el) => el === document.activeElement), true);
}, { clockTime: new Date('2026-10-05T22:30:00Z') }));
