import { test, before, after } from 'node:test';
import assert from 'node:assert/strict';
import { uuid } from '../../shared/ids.js';
import { dateInTz } from '../../shared/dates.js';
import { launch, withPhone, waitSaved, waitStatus, TZ } from './harness.js';
let browser;
before(async () => { browser = await launch(); });
after(async () => browser.close());

test('text edits stay in the original task, preserve formatting/children and recover offline; only arrow expands', () => withPhone(browser, async ({ app, page, context }) => {
  const id = uuid(), taskId = uuid(), childId = uuid();
  const task = (id, text) => ({ type: 'taskItem', attrs: { id, checked: false }, content: [{ type: 'paragraph', content: [{ type: 'text', text, marks: [{ type: 'bold' }] }] }] });
  const parent = task(taskId, 'Write poster');
  parent.content.push({ type: 'taskList', content: [task(childId, 'Nested action')] });
  await app.api('PUT', `/api/notes/${id}`, { baseRevision: 0, kind: 'note', title: 'Source', date: dateInTz(new Date(), TZ), tags: ['test'], docFormat: 1, doc: { type: 'doc', content: [{ type: 'taskList', content: [parent] }] } });
  await page.goto(`${app.url}/#/`);
  const row = page.getByTestId('task-row').filter({ hasText: 'Write poster' });
  await row.getByTestId('task-edit-text').tap();
  const editor = page.getByTestId('task-text-editor');
  await editor.waitFor();
  assert.equal(await row.getByTestId('task-details').count(), 0);
  await context.setOffline(true);
  await editor.press('End'); await page.keyboard.type(' today');
  await waitStatus(page, 'offline');
  await editor.press('Control+z');
  assert.equal(await editor.innerText(), 'Write poster');
  await editor.press('Control+Shift+z');
  assert.match(await editor.innerText(), /Write poster today/);
  await row.getByTestId('task-text-done').tap();
  await context.setOffline(false); await waitSaved(page, 15000);
  const stored = (await app.api('GET', `/api/notes/${id}`)).json.note.doc.content[0].content[0];
  assert.equal(stored.attrs.id, taskId);
  assert.equal(stored.content[1].content[0].attrs.id, childId);
  assert.equal(stored.content[0].content[0].marks[0].type, 'bold');
  assert.ok(!('content' in stored.attrs));
  await row.getByTestId('task-expand').tap();
  await row.getByTestId('task-details').waitFor();
  await page.goto(`${app.url}/#/n/${id}`);
  await page.getByRole('textbox', { name: 'Note text', exact: true }).waitFor();
  assert.match(await page.getByRole('textbox', { name: 'Note text', exact: true }).innerText(), /Write poster today/);
  assert.deepEqual(page.errors, []);
}));
