import { test, before, after } from 'node:test';
import assert from 'node:assert/strict';
import { launch, withPhone, waitSaved } from './harness.js';
import { uuid } from '../../shared/ids.js';
let browser;
before(async () => { browser = await launch(); });
after(async () => { await browser.close(); });
test('history filters timestamps in home timezone, expands older range, keeps unknown dates and restores tasks in place', () => withPhone(browser, async ({ app, page }) => {
  const noteId = uuid();
  const entries = [['Recent completed', { checked: true, completedAt: '2026-10-05T18:00:00.000Z' }], ['Older dismissed', { checked: false, dismissedAt: '2026-09-20T18:00:00.000Z' }], ['Imported checked', { checked: true }], ['Near midnight', { checked: true, completedAt: '2026-10-05T05:00:00.000Z' }]];
  const tasks = entries.map(([text, attrs]) => ({ type: 'taskItem', attrs: { id: uuid(), ...attrs }, content: [{ type: 'paragraph', content: [{ type: 'text', text }] }] }));
  await app.api('PUT', `/api/notes/${noteId}`, { baseRevision: 0, kind: 'note', date: '2026-10-05', tags: ['test'], docFormat: 1, doc: { type: 'doc', content: [{ type: 'taskList', content: tasks }] } });
  await page.goto(`${app.url}/#/n/${noteId}`);
  const archive = page.getByTestId('task-archive');
  await archive.locator(':scope > summary').tap();
  await page.getByTestId('archive-calendar').tap();
  await page.getByTestId('archive-from').fill('2026-10-05');
  await page.getByTestId('archive-to').fill('2026-10-05');
  assert.equal(await page.getByTestId('archive-task').count(), 2, 'one dated item plus unknown date, not UTC midnight');
  assert.match(await archive.innerText(), /Date not recorded/i);
  await page.getByRole('button', { name: 'Done', exact: true }).tap();
  await page.getByTestId('archive-older').tap();
  await page.getByTestId('archive-calendar').tap();
  assert.equal(await page.getByTestId('archive-from').inputValue(), '2026-09-20');
  await page.getByRole('button', { name: 'Done', exact: true }).tap();
  assert.equal(await page.getByTestId('archive-task').count(), 4);
  await archive.getByRole('button', { name: 'Dismissed', exact: true }).tap();
  assert.equal(await page.getByTestId('archive-task').count(), 1);
  await page.getByTestId('archive-task').getByRole('button', { name: 'Bring back' }).tap();
  await waitSaved(page);
  const doc = (await app.api('GET', `/api/notes/${noteId}`)).json.note.doc;
  assert.equal(doc.content[0].content[1].attrs.id, tasks[1].attrs.id);
  assert.equal(doc.content[0].content[1].attrs.checked, false);
  assert.equal(doc.content[0].content[1].attrs.dismissedAt, undefined);
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
}));
test('checking in the note records a completion timestamp, undo clears it and redo restores it', () => withPhone(browser, async ({ app, page }) => {
  const id = uuid(), taskId = uuid();
  await app.api('PUT', `/api/notes/${id}`, { baseRevision: 0, kind: 'note', date: '2026-10-05', tags: ['test'], docFormat: 1, doc: { type: 'doc', content: [{ type: 'taskList', content: [{ type: 'taskItem', attrs: { id: taskId, checked: false }, content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Check this' }] }] }] }] } });
  await page.goto(`${app.url}/#/n/${id}`);
  const editor = page.locator('.note-text[contenteditable="true"]');
  await editor.locator('li input').check();
  await waitSaved(page);
  const attrs = () => app.api('GET', `/api/notes/${id}`).then((r) => r.json.note.doc.content[0].content[0].attrs);
  const checked = await attrs(); assert.ok(checked.completedAt);
  await page.getByTestId('tb-undo').tap(); await waitSaved(page);
  assert.equal((await attrs()).completedAt, undefined);
  await page.getByTestId('tb-redo').tap(); await waitSaved(page);
  assert.equal((await attrs()).completedAt, checked.completedAt);
}));
