import { test, before, after } from 'node:test';
import assert from 'node:assert/strict';
import { launch, withPhone, waitSaved, paragraphDoc, waitStatus } from './harness.js';
import { uuid } from '../../shared/ids.js';
let browser;
before(async () => { browser = await launch(); });
after(async () => { await browser.close(); });
const makeDoc = (ids) => ({ type: 'doc', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Keep these notes intact.' }] }, { type: 'taskList', content: ids.map((id, i) => ({ type: 'taskItem', attrs: { id, checked: false }, content: [{ type: 'paragraph', content: [{ type: 'text', text: `Task ${i + 1}`, marks: [{ type: 'bold' }] }] }] })) }] });
async function seed(app, doc, tags = ['test'], title = 'Test note') {
  const id = uuid();
  const result = await app.api('PUT', `/api/notes/${id}`, { baseRevision: 0, kind: 'note', date: '2026-10-05', title, doc, docFormat: 1, tags });
  assert.equal(result.status, 200);
  return id;
}
test('dismiss is separate from done, persists, can be brought back; delete requires confirmation and preserves history', () => withPhone(browser, async ({ app, page }) => {
  const ids = [uuid(), uuid()];
  const noteId = await seed(app, makeDoc(ids));
  await page.goto(`${app.url}/#/tasks`);
  const row = () => page.getByTestId('task-row').filter({ hasText: 'Task 1' });
  await row().getByTestId('task-expand').tap();
  await row().getByTestId('task-dismiss').tap();
  await waitSaved(page);
  await page.getByTestId('toggle-dismissed').tap();
  assert.equal(await row().getByTestId('chip-dismissed').count(), 1);
  let note = (await app.api('GET', `/api/notes/${noteId}`)).json.note;
  assert.equal(note.doc.content[1].content[0].attrs.checked, false);
  assert.ok(note.doc.content[1].content[0].attrs.dismissedAt);
  assert.equal(note.doc.content[1].content[0].content[0].content[0].marks[0].type, 'bold');
  await page.reload();
  await page.getByTestId('toggle-dismissed').tap();
  await row().getByTestId('task-expand').tap();
  await row().getByTestId('task-dismiss').tap();
  await waitSaved(page);
  await row().getByTestId('task-expand').tap();
  await row().getByTestId('task-delete').tap();
  await row().getByTestId('task-delete-cancel').tap();
  assert.equal((await app.api('GET', `/api/notes/${noteId}`)).json.note.doc.content[1].content.length, 2);
  await row().getByTestId('task-delete').tap();
  await row().getByTestId('task-delete-confirm').tap();
  await waitSaved(page);
  note = (await app.api('GET', `/api/notes/${noteId}`)).json.note;
  assert.equal(note.doc.content[1].content.length, 1);
  assert.equal(note.doc.content[1].content[0].attrs.id, ids[1]);
  const versions = app.db.prepare('SELECT doc FROM note_versions WHERE note_id = ? ORDER BY rowid DESC').all(noteId);
  assert.ok(versions.some((v) => v.doc.includes(ids[0])), 'deleted task can be recovered even inside snapshot interval');
}));
test('task dismissal and deletion in the editor are undoable and survive a connection interruption', () => withPhone(browser, async ({ app, page, context }) => {
  const taskId = uuid();
  const noteId = await seed(app, makeDoc([taskId]));
  await page.goto(`${app.url}/#/n/${noteId}`);
  const editor = page.locator('.note-text[contenteditable="true"]');
  await editor.locator('li p').tap();
  await page.getByTestId('tb-taskdates').tap();
  await page.getByTestId('task-dismiss').tap();
  await waitSaved(page);
  assert.equal(await editor.locator('[data-dismissed-at]').count(), 1);
  await page.getByTestId('tb-undo').tap();
  assert.equal(await editor.locator('[data-dismissed-at]').count(), 0);
  await page.getByTestId('tb-redo').tap();
  assert.equal(await editor.locator('[data-dismissed-at]').count(), 1);
  assert.equal(await editor.locator('[data-dismissed-at]').isVisible(), false);
  await page.getByTestId('task-archive').locator(':scope > summary').tap();
  await page.getByTestId('archive-calendar').tap();
  await page.getByTestId('task-archive').getByRole('button', { name: 'All dates', exact: true }).tap();
  await page.getByTestId('task-archive').getByRole('button', { name: 'Bring back', exact: true }).tap();
  await editor.locator('li p').tap();
  await page.keyboard.press('End');
  await page.keyboard.press('Enter');
  await page.keyboard.type('New active task');
  assert.equal(await editor.locator('li[data-dismissed-at]').count(), 0, 'restored task and new task are active');
  await waitSaved(page);
  await editor.locator('li p').first().tap();
  await page.getByTestId('tb-taskdates').tap();
  await context.setOffline(true);
  await page.getByTestId('task-delete').tap();
  await page.getByTestId('task-delete-confirm').tap();
  await waitStatus(page, 'offline');
  assert.equal(await editor.locator('li').count(), 1);
  await page.getByTestId('tb-undo').tap();
  assert.equal(await editor.locator('li').count(), 2);
  await page.getByTestId('tb-redo').tap();
  assert.equal(await editor.locator('li').count(), 1);
  await page.route('**/api/**', (route) => route.abort('connectionfailed'));
  await context.setOffline(false); // the app shell can load; the server API remains unreachable
  await waitStatus(page, 'offline');
  await page.waitForTimeout(500); // allow the browser's durable pending write to finish
  await page.reload();
  await editor.waitFor();
  assert.equal(await editor.locator('li').count(), 1, 'phone copy survives reopening offline');
  await page.unroute('**/api/**');
  await page.getByTestId('global-status').tap();
  await waitSaved(page, 15000);
  assert.match(app.docText(noteId), /New active task/);
  assert.doesNotMatch(app.docText(noteId), /Task 1/);
}));
test('People lists only people-tagged notes and opens the same editable note', () => withPhone(browser, async ({ app, page }) => {
  const noteId = await seed(app, paragraphDoc('Fictional profile'), ['05 People/friends'], 'Zed');
  await seed(app, paragraphDoc('Other profile'), ['05 People/css'], 'Ava');
  await seed(app, paragraphDoc('Other note'), ['10 School']);
  await page.goto(`${app.url}/#/people`);
  await page.getByTestId('person-note').first().waitFor();
  assert.equal(await page.getByTestId('person-note').count(), 2);
  assert.deepEqual(await page.locator('.person-card .note-title').allInnerTexts(), ['Ava', 'Zed']);
  await page.getByRole('button', { name: 'Friends', exact: true }).tap();
  await page.waitForFunction(() => document.querySelectorAll('[data-testid="person-note"]').length === 1);
  assert.match(await page.getByTestId('person-note').innerText(), /Zed/);
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
  await page.getByLabel('Search people').fill('missing');
  await page.getByText('No people match.').waitFor();
  await page.getByLabel('Search people').fill('Fictional');
  await page.getByTestId('person-note').tap();
  await page.locator('.note-text[contenteditable="true"]').waitFor();
  assert.equal(await page.evaluate(() => location.hash), `#/n/${noteId}`);
}));
test('deleting the only task leaves editable text, and undo restores its stable ID', () => withPhone(browser, async ({ app, page }) => {
  const taskId = uuid();
  const doc = makeDoc([taskId]); doc.content.shift();
  const noteId = await seed(app, doc);
  await page.goto(`${app.url}/#/n/${noteId}`);
  const editor = page.locator('.note-text[contenteditable="true"]');
  await editor.locator('li p').tap();
  await page.getByTestId('tb-taskdates').tap();
  await page.getByTestId('task-delete').tap();
  await page.getByTestId('task-delete-confirm').tap();
  assert.equal(await editor.locator('li').count(), 0);
  assert.equal(await editor.locator('p').count(), 1);
  await page.getByTestId('tb-undo').tap();
  await waitSaved(page);
  assert.equal((await app.api('GET', `/api/notes/${noteId}`)).json.note.doc.content[0].content[0].attrs.id, taskId);
}));
