import { test, before, after } from 'node:test';
import assert from 'node:assert/strict';
import { launch, withPhone, waitSaved, caret } from './harness.js';
import { uuid } from '../../shared/ids.js';
let browser;
before(async () => { browser = await launch(); });
after(async () => { await browser.close(); });
const para = (text) => ({ type: 'paragraph', content: text ? [{ type: 'text', text }] : undefined });
test('completion looks like a bullet, dismissal hides in the note, history restores, and hidden-only notes stay writable', () => withPhone(browser, async ({ app, page }) => {
  const id = uuid(), taskId = uuid();
  await app.api('PUT', `/api/notes/${id}`, { baseRevision: 0, kind: 'note', title: 'Presentation', date: '2026-10-05', tags: [], docFormat: 1, doc: { type: 'doc', content: [{ type: 'taskList', content: [{ type: 'taskItem', attrs: { id: taskId, checked: false }, content: [para('Archive me')] }] }] } });
  await page.goto(`${app.url}/#/n/${id}`);
  const editor = page.locator('.note-text[contenteditable="true"]');
  await editor.locator('input[type=checkbox]').check(); await waitSaved(page);
  assert.equal(await editor.locator('input[type=checkbox]').isVisible(), false);
  assert.equal(await editor.getByRole('img', { name: 'Completed task', exact: true }).isVisible(), true);
  assert.equal(await editor.locator('.task-actions').isVisible(), false);
  await page.getByTestId('tb-undo').tap();
  await editor.locator('li p').tap();
  await page.getByTestId('tb-taskdates').tap(); await page.getByTestId('task-dismiss').tap(); await waitSaved(page);
  assert.equal(await editor.locator('li').isVisible(), false);
  await editor.locator(':scope > p').tap(); await page.keyboard.type('Keep writing'); await waitSaved(page);
  assert.equal((await caret(page)).focused, true);
  const saved = (await app.api('GET', `/api/notes/${id}`)).json.note.doc;
  assert.equal(saved.content[0].content[0].attrs.id, taskId);
  assert.ok(saved.content[0].content[0].attrs.dismissedAt);
  await page.reload(); await editor.waitFor();
  assert.equal(await editor.locator('li').isVisible(), false);
  assert.match(await editor.innerText(), /Keep writing/);
  const archive = page.getByTestId('task-archive'); await archive.locator(':scope > summary').tap();
  await page.getByTestId('archive-calendar').tap();
  await archive.getByRole('button', { name: 'All dates', exact: true }).tap();
  await archive.getByRole('button', { name: 'Bring back', exact: true }).tap(); await waitSaved(page);
  assert.equal(await editor.locator('li').isVisible(), true);
  assert.equal((await app.api('GET', `/api/notes/${id}`)).json.note.doc.content[0].content[0].attrs.id, taskId);
}));
